config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here

    # /
    path("", include("djangogram.users.urls", namespace="users")),
    # /posts/
    path("posts/", include("djangogram.posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('pages/', views.home, name='home'),
]

djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name='main'), # view함수 내부의 main함수를 호출하니까 main함수를 만들고 템플릿과 연결
    path('signup/', views.signup, name='signup'),
]

djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model

# Create your models here.

# >> 데이터 생성날짜, 변경날짜 <<
class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    # 이 옵션을 주면 TimeStamedModels는 단독으로 테이블이 만들어지지 않을 것임
    class Meta:
        abstract = True

# >> 포스트 모델 <<
class Post(TimeStamedModel):
    author = models.ForeignKey(
                user_model.User,
                null=True,
                on_delete=models.CASCADE, # 외래키를 갖는 특정유저가 삭제되면 어떻게 처리가 될 것인가를 알려주는 옵션
                related_name='post_author'
            )
    image = models.ImageField(blank=True)
    caption = models.TextField(blank=True)
    image_likes = models.ManyToManyField(user_model.User, related_name='post_image_likes')

# >> 댓글 모델 <<
class Comment(TimeStamedModel):
    author = models.ForeignKey(
                user_model.User,
                null=True,
                on_delete=models.CASCADE, # 외래키를 갖는 특정유저가 삭제되면 어떻게 처리가 될 것인가를 알려주는 옵션
                related_name='comment_author'
            )
    posts = models.ForeignKey(
                Post,
                null=True,
                on_delete=models.CASCADE, # 외래키를 갖는 특정포스트가 삭제되면 어떻게 처리가 될 것인가를 알려주는 옵션
                related_name='comment_post'
            )
    contents = models.TextField(blank=True)

djangogram/users/models.py
from typing import BinaryIO
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom'),
    ]

    #: First and last name do not cover name patterns around the globe
    #: >> 유저정보 <<
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo = models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES ,max_length=255)

    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

djangogram/users/forms.py
# from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_messages = forms.UserCreationForm.error_messages.update(
        {"duplicate_username":_("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

        def clean_username(self):
            username = self.cleaned_data["username"]

            try:
                User.objects.get(username=username)
            except User.DoesNotExist:
                return username

            raise ValidationError(self.error_messages["duplicate_username"])

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','name','username','password']

        # labels = {
        #     'email': '이메일 주소',
        #     'name': '성명',
        #     'username': '사용자 이름',
        #     'password': '비밀번호'
        # }

        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder': '이메일 주소'}),
            'name': django_forms.TextInput(attrs={'placeholder': '성명'}),
            'username': django_forms.TextInput(attrs={'placeholder': '사용자 이름'}),
            'password': django_forms.PasswordInput(attrs={'placeholder': '비밀번호'}),
        }

        def save(self, commit=True):
            user = super().save(commit=False)
            user.set_password(self.cleaned_data['password'])
            if commit:
                user.save()
            return user  

djangogram/posts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'posts/index.html')

def home(request):
    return render(request, 'pages/home.html')    

djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import SignUpForm

def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html') # 호출되는 템플릿을 작성해야함
        # 페이지를 보기위한 GET 방식 요청은 이 위치에서 처리

    elif request.method == 'POST':
        # 로그인 요청에 따른 POST 방식은 이 위치에서 처리
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('posts:index'))
        
        else:
        # Return an 'invalid login' error message.
            return render(request, 'users/main.html')

# 로그인 view
def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'users/signup.html', {'form': form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
        
            user = authenticate(request, username=username, password=password)

            if user is not None:
               login(request, user)
               return HttpResponseRedirect(reverse('posts:index'))

        return render(request, 'users/main.html')

djangogram/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}djangogram{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="Daniel Roy Greenfeld">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">djangogram</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

djangogram/templates/pages/about.html
{% extends "base.html" %}

djangogram/templates/pages/home.html
{% extends "base.html" %}
<!-- <a href="{% url 'index' %}">Home</a>. -->

djangogram/templates/posts/index.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <!-- Favicon-->
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon/favicon.ico' %}" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="#page-top">NONAME</a>
      <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
        aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">FOOD</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#info">INFO</a></li>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#post">POST</a></li>
          <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">CONTACT</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead-->
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
      <!-- Masthead Avatar Image-->
      <img class="masthead-avatar mb-5" src="{% static 'images/avataaars.svg' %}" alt="..." />
      <!-- Masthead Heading-->
      <h1 class="masthead-heading text-uppercase mb-0">DevKFQ_Student</h1>
      <!-- Icon Divider-->
      <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
      </div>
      <!-- Masthead Subheading-->
      <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>
    </div>
  </header>

  <!-- 수업시간 -->
  <input type='text'> inch
  <button>계산</button>
  <p></p>

  검색어입력:<input type='text' name="search">
  <script>
    const input = document.querySelector('input');
    const button = document.querySelector('button');
    button.addEventListener('click', () => {
      let value = input.value;
      input.value = value * 2.54;
    });
    // 변환공식: inch*2.54=>cm

    const input = document.querySelector('[name=search]');

    input.addEventListener('keyup', (event) => {
      if (event.keyCode == 32) {
        event.currentTarget.value += ', #';
      }
      console.log(event.keyCode);
    });

    input.addEventListener('focus', (event) => {
      let search = event.currentTarget.value;
      if (search == '') {
        event.currentTarget.value = '#';
      }
    });
  </script>
  <!-- 수업시간 -->

  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'js/scripts.js' %}"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

djangogram/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="content">
        <!-- content block 태그에 로그인과 가입화면 
        이 부분만 변경되고 타이틀과 푸터는 고정-->
        {% block content %} {% endblock %}
    </div>

    {% include "users/footer.html" %}
</body>
</html>

djangogram/templates/users/footer.html
<!-- footer는 include를 통해 base에 포함시킴
바로 작성해도 되지만 include를 사용하면 유지보수가 용이 -->
<footer>
    <div class="list">
        <ul>
            <li><a href = "#">소개</a></li>&nbsp;
            <li><a href = "#">블로그</a></li>&nbsp;
            <li><a href = "#">채용정보</a></li>&nbsp;
            <li><a href = "#">도움말</a></li>&nbsp;
            <li><a href = "#">API</a></li>&nbsp;
            <li><a href = "#">개인정보처리방침</a></li>&nbsp;
            <li><a href = "#">약관</a></li>&nbsp;
            <li><a href = "#">인기 계정</a></li>&nbsp;
            <li><a href = "#">해시태그</a></li>&nbsp;
            <li><a href = "#">위치</a></li>
        </ul>
    </div>
    <br>
    <div class="company">@ 2021 Djangogram from SH</div>
</footer>

djangogram/templates/users/main.html
{% extends "users/base.html" %}

<h1>Here is SignIn(Login) page</h1>
{% block title %}
Log in
{% endblock title %}

{% block content %}
<div class="auth">
    <h1 class="auth-heading">Djangogram</h1>
    <form action="{% url 'users:main' %}" method='post'>
        {% csrf_token %}
        <div class="auth-login1">
            <input type='username' name='username' placeholder="전화번호, 사용자 이름 또는 이메일">
        </div>

        <div class="auth-login2">
            <input type='password' name='password' placeholder="비밀번호">
        </div>

        <!-- checkbox 추가 -->
        <div class="auth-login-checkbox">
            <label class="checkbox">
                <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe">Remember me
            </label>
        </div>

        <div class="auth-login3">
            <button type='submit'>로그인</button>
        </div>
    </form>

</div>

<div class="auth_link">
    <p>
        계정이 없으신가요?
        <a href="{% url 'users:signup' %}">가입하기</a>
    </p>
</div>
{% endblock content %}

djangogram/templates/users/signup.html
{% extends "users/base.html" %}

<h1>Here is SignUp page</h1>
{% block title %}
Sing Up
{% endblock title %}

{% block content %}
<div class="auth">
    <form action="{% url 'users:signup' %}" method='post'>
        {% csrf_token %}
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field }}
        </div>
        {% endfor %}
        <input type='submit' value='Sign up'>
    </form>
</div>
<div class="auth_link">
    <a href="{% url 'users:main' %}">Login</a>
</div>
{% endblock content %}

djangogram/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

djangogram/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}